### PR TITLE
docs(leader-election): added missing property in typedefinition 

### PR DESCRIPTION
**Pull request by Xesenix**
and additional documentation

### CODE REVIEW

**Comment by Xesenix** [comment]
Not sure why there is no output for one of your test process. I don't think I have touched anything that could spoil tests. Any advice?

**Comment by pubkey** [comment]
@Xesenix sometimes they fail when travis has a huge load and the servers are too slow.
I will restart until it passes.

**Comment by pubkey** [comment]
Thanks for the PR btw. Can you add to the example that the options are optional?

**Comment by Xesenix** [comment]
Ok, but I will that in the evening when I get back home.

**Comment by Xesenix** [comment]
Updated options description comments in readme.

**Comment by pubkey** [comment]
Thank you for the great work. I merged this. I will now update the dependencies and then publish a new release.

**Pull request merged**
