### PR TITLE
Remove broken check

### PR DESCRIPTION
**Pull request by mrlika**
@pubkey

## This PR contains:
 - A BUGFIX

## Describe the problem you have without this PR

No `window` object in a service worker context causes the service worker to fail to detect native support.

The check, for some reason, was not removed in this PR: https://github.com/pubkey/broadcast-channel/pull/1037

## Todos
- [ ] Tests
- [ ] Changelog

### CODE REVIEW

**Comment by pubkey** [comment]
This is intentional. The nodejs worker only works in worker threads.

**Comment by pubkey** [comment]
@mrlika sorry I first missunderstood the problem.
Can you check why the CI is failing?

**Comment by mrlika** [comment]
The test needs to be corrected. In Node v18 BroadcastChannel is defined in global scope as a native implementation. If the native implementation is used, `clearNodeFolder` should do nothing as in the browser context.

**Comment by mrlika** [comment]
@pubkey, I fixed failing tests to force the use of the `node` method in the `isNode` environment because after my change default environment for Node.js v18 is `native` (not `node` as it was before)

Please confirm that in Node.js v18 default should be `native` and not `node`.

**Comment by mrlika** [comment]
Ok. Fixed.
- `typeof window !== 'undefined'` is for regular browser environment
- `typeof self !== 'undefined'` is for Service and Web Worker environments
- then check `typeof BroadcastChannel === 'function'` to fallback to indexedDB implementation in Safari <= 15.3, which is missing BrowserChannel API

**Comment by pubkey** [comment]
Merged and released @mrlika  . Thank you, please test the new release.

**Pull request merged**
