### PR TITLE
Add a ready to use browser version to build.

### PR DESCRIPTION
**Pull request by rob-64**

### CODE REVIEW

**Comment by rob-64** [comment]
@pubkey im not sure why the travisci is failing, I didn't actually touch anything there

**Comment by pubkey** [comment]
@rob-64 I restarted it. lets try again.

**Comment by rob-64** [comment]
@pubkey it failed again... Anything I can do ?

**Comment by rob-64** [comment]
@pubkey any update on whats wrong here?

**Comment by pubkey** [comment]
https://travis-ci.org/pubkey/broadcast-channel/jobs/545021417
I think there was a change in travis which is causing this.

**Comment by pubkey** [comment]
@rob-64 I could fix this. Please resolve the conflicts

**Comment by pubkey** [comment]
@rob-64 sometimes travis is too slow to run the browser-tests. I will restart some times

**Comment by rob-64** [comment]
@pubkey Can you do a release so the browser ready version is available on NPM? I would really appreciate it

**Comment by pubkey** [comment]
yes. I released `2.2.0` a few secs ago.

**Pull request merged**
