### PR TITLE
FIX #22 require is not defined

### LINKED ISSUE #22: ReferenceError: require is not defined
My browser is throwing the error mentioned due to this line:
https://github.com/pubkey/broadcast-channel/blob/master/src/method-chooser.js#L15

FWIW I'm using Rollup + StencilJS.

PR incoming 💣

### PR DESCRIPTION
**Pull request by snaptopixel**

### CODE REVIEW

**Comment by pubkey** [comment]
Please do not commit generated files, like the ones in the dist-folder.

**Comment by pubkey** [comment]
Why does this PR remove the docs-folder?

**Comment by snaptopixel** [comment]
I've updated it to not include any built files @pubkey, I can move that part to a different PR if it clouds the issue.

**Comment by snaptopixel** [comment]
I'm not sure why Travis is stuck on the Linux builds...

**Comment by pubkey** [comment]
The dist-folder is committed so people can use github instead of npm as registry. The docs-folder is comitted becaus github-pages serves everything from that folder which is the example pages.
I'm trying to fix the ci..

**Comment by pubkey** [comment]
Please remove everything from the PR which is not related to #22

**Comment by snaptopixel** [comment]
Thanks @pubkey I'll clean up and open another PR. The dist folder can be safely removed because I'm adding the `prepare` script which will build the lib when installed from github.

**Comment by pubkey** [comment]
@snaptopixel I don't know if I understand the behavor of the prepare-script correctly. But I think this would require the user to have installed all dev-dependencies?

**Comment by pubkey** [comment]
@snaptopixel  I removed the resolve-plugin [here](https://github.com/pubkey/broadcast-channel/commit/d835545e236da1e8050667931bf9f6b5e2cacb85) but the rollup-build still works, see [here](https://travis-ci.org/pubkey/broadcast-channel/builds/572902425). What other rollup-config do you have?

**Pull request closed without merging**
